### ISSUE TITLE
Where is json_minify.py?

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/jupyterlab_server#134]
I've started packaging jupyterlab_server for Debian, and saw json_minify.py was MIT-licensed... but couldn't find that file : perhaps it was used at some point and the notice wasn't removed from LICENSE?

**Comment by afshin** [comment]
Thanks for the heads up @SnarkBoojum!

**Comment by jasongrout** [comment]
@SnarkBoojum - thank you very much for helping us improve the quality of our packages. I've been really impressed with how Debian packagers help upstream projects improve, and you have been particularly helpful. Thanks!
