### ISSUE TITLE
This seems to contradict the docs

### ISSUE THREAD

**Issue by abarrafo** [jupyterlab/jupyterlab_server#147]
https://github.com/jupyterlab/jupyterlab_server/blob/1f3113dfed1984d3c7c5e259c563293d35c2aedd/jupyterlab_server/listings_handler.py#L38

Should this be `allowlist_uris`? as documented here: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#listing-configuration

**Comment by abarrafo** [comment]
In fact: 

```
jupyter lab --LabServerApp.blocklist_uris=http://example.com/blocklist.json
[W 2021-01-07 19:10:53.523 LabApp] Config option `blocklist_uris` not recognized by `LabApp`.  Did you mean one of: `blacklist_uris, whitelist_uris`?
```

Docs might be wrong

**Comment by fcollonval** [comment]
The documentation was updated in https://github.com/jupyterlab/jupyterlab/pull/9221
