### ISSUE TITLE
Conda-Forge Installation Error

### ISSUE THREAD

**Issue by adwiputra** [jupyterlab/jupyterlab_server#148]
Hi, I have been trying to update my jupyter-server in my conda environment as one of the dependencies of another package. However, the installation of the package failed as shown below:

![image](https://user-images.githubusercontent.com/14678187/104058322-64a7b480-51a8-11eb-90fc-c18d36ac9b2b.png)

Is there any workaround to this?

**Comment by blink1073** [comment]
This sounds like an issue in your conda environment, similar to https://github.com/conda/conda/issues/9693.  I just tried `conda install -c conda-forge jupyterlab_server==2.1.0` in clean python 3.7 environment and it installed successfully

**Comment by krassowski** [comment]
@adwiputra what is your Python version?

**Comment by fcollonval** [comment]
I close this one as answered. Please reopen if this is not the case.
