### ISSUE TITLE
CP949 encoding error on Windows

### ISSUE THREAD

**Issue by takavfx** [jupyterlab/jupyterlab_server#155]
# Reproduce

1. Install JupyterLab by pip (This stage doens't outputs error below)
2. Install jupyterlab-kite by pip
3. Luanch JupyterLab (The error occurs here)
4. (Install jupyterlab_kite extension by `jupyter labextension install "@kiteco/jupyterlab-kite"`)

* Windows 10
* jupyterlab==3.0.7
* jupyter-server==1.2.2
* jupyterlab-kite==2.0.2

# Error Message

This is similar issue of [JupyterLab issue #9171](https://github.com/jupyterlab/jupyterlab/issues/9171).

And the actual error output is:
```
      File "f:\develop\.venv\lib\site-packages\jupyterlab_server\config.py", line 37, in get_federated_extensions
        pkgdata = json.load(fid)
      File "C:\Users\takanori\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 523: illegal multibyte sequence
```

# Solution

I could fix this issue by altering the line as: (I added `encoding=` argument.)

```python
def get_federated_extensions(labextensions_path):
    ~~~
            with open(ext_path, encoding="utf-8") as fid:
                pkgdata = json.load(fid)
    ~~~
```

I pushed the fixed code on [my forked repo](https://github.com/takavfx/jupyterlab_server/blob/fix/cp949_encoding_error/jupyterlab_server/config.py#L81).

**Comment by jasongrout** [comment]
Thanks! Can you submit a PR with that change?

**Comment by jasongrout** [comment]
In fact, it looks like there are several other instances of open() in that file that also should be updated. If you are making a PR, could you update those as well?

**Comment by takavfx** [comment]
Sure! I'll fix them so please give me some time.
