### ISSUE TITLE
What is the difference between jupyterlab_server and jupyter_server? 

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab_server#163]
Per my knowledge, JupyterLab 3 is using jupyter_server.

**Comment by Zsailer** [comment]
[jupyter_server](https://github.com/jupyter-server/jupyter_server) offers the core Tornado server, web application, and REST API for all Jupyter-related web applications.

`jupyterlab_server` is extends `jupyter_server`'s core server by adding extra endpoints, handlers, and config that are used by JupyterLab.

Combined, `jupyter_server` + `jupyterlab_server` provides the backend to JupyterLab. JupyterLab is mostly a frontend/client for this "super server"; it requires both pieces to work.

**Comment by dclong** [comment]
Thank you for the explanation!
