### ISSUE TITLE
gettext not have dpgettext attribute when using python3.7

### ISSUE THREAD

**Issue by eastonsuo** [jupyterlab/jupyterlab_server#211]
## Description

when using lower version of python, a error may be raised beacause python libraries is not compatiable with jupyterlab_server.

for example, when use gettext for translation, the dpgettext is add after python 3.7.

should there be some warning for use or do some code change for compatibility?

**Comment by krassowski** [comment]
Thanks for reporting this issue, you are right this should not raise an error on 3.7! This was fixed in https://github.com/jupyterlab/jupyterlab_server/pull/213 - closing this one.
