### ISSUE TITLE
Hardcoded logging level

### ISSUE THREAD

**Issue by rvalieris** [jupyterlab/jupyterlab_server#268]
## Description

It seems that jupyterlab server is setting the logging level hardcoded to INFO:

https://github.com/jupyterlab/jupyterlab_server/blob/93703e2242788c6b8083b351e25ec8113930420d/jupyterlab_server/process.py#L35

I was looking at a jupyter extension that was priting a lot of logs on the terminal, trying to find a way to silence these logs and I noticed the extension was using `logging.info()`, I assumed setting `--log-level WARN` would be enough but the logs kept appearing, eventually I found this code quoted above, I'm not 100% sure this is the culprit because its a lot of code to follow on but it seems the most likely.

## Reproduce

1. a jupyter extension that prints `print(logging.getLogger())`
2. run `jupyter lab --log-level WARN`
3. notice that the logger printed have the INFO log level `<RootLogger root (INFO)>`

I also tried `jupyter lab --log-level WARN --Application.log_level=WARN --JupyterApp.log_level=WARN --ExtensionApp.log_level=WARN --LabServerApp.log_level=WARN --LabApp.log_level=WARN`
with the same result.

## Expected behavior

I expected that the `--log-level` command line args would set the logging to the requested log level

## Context

- Operating System and version: Ubuntu 20.04 
- Browser and version: Firefox 99 
- JupyterLab version: 3.3.4 
- JupyterLab server: 2.13.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by blink1073** [comment]
Thanks for the report @rvalieris!  Can you try commenting that line out in your install and seeing if it solves your issue?  If it does, we can create a function called `get_log()` and call that to set up the default logger [here](https://github.com/jupyterlab/jupyterlab_server/blob/93703e2242788c6b8083b351e25ec8113930420d/jupyterlab_server/process.py#L95).

**Comment by rvalieris** [comment]
yes kinda, if I comment out that line the uninitialized logger defaults to WARN, which does silence the logs from the extension, but the level doesn't change with the command line args.

am I right to assume `--log-level` should set the level of the root logger ? the level of the `getLogger("jupyterlab")` also doesn't change with `--log-level`. (but inherits from root)

but printing `logging.root.manager.loggerDict` reveals that there is a `getLogger("ServerApp")` that is being initialized with the correct level (somewhere else ?) so I guess the root logger should remain uninitialized after all ?

**Comment by blink1073** [comment]
Wherever the `ProcessApp` is being instantiated, the caller should be passing a configured logger down, which should be the `ServerApp` logger.  I think the next thing to try would be to search for usages of `ProcessApp` in `JupyterLab` itself and see if the `log` is being passed in correctly.

**Comment by rvalieris** [comment]
ah yes, the logger is being passed correctly, the `getLogger("jupyterlab")` is just the plan B in case the logger is not passed for some reason. 

I have a working patch with a `get_log` function, should I submit a PR ?

**Comment by blink1073** [comment]
Yes, please!
