### ISSUE TITLE
page_config.json should support json5

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab_server#377]
### Problem

Similar to overrides, `page_config.json` should also support json5 so that comments can be added.

### Proposed Solution

All json configs should always support json5. Maybe we add a common codepath to enforce this? I.e. instead of doing something like [this](https://github.com/jupyterlab/jupyterlab_server/blob/eb37a21d1deaf449074da2d087b57a773e26fdaa/jupyterlab_server/config.py#L91) we refactor [this](https://github.com/jupyterlab/jupyterlab_server/blob/eb37a21d1deaf449074da2d087b57a773e26fdaa/jupyterlab_server/settings_utils.py#L291) to be reused.

**Comment by peytondmurray** [comment]
I'm happy to take this on! Refactoring now to allow json5 everywhere.
