### ISSUE TITLE
Support for openapi-core-0.17*

### ISSUE THREAD

**Issue by mgorny** [jupyterlab/jupyterlab_server#400]
### Problem

The package currently requires openapi-core-16*. However, 0.17* was released in March already.

### Proposed Solution

Add support for openapi-core-0.17*.

### Additional context

n/a

**Comment by bollwyvl** [comment]
PRs welcome, but these dependencies were pinned due to the highly unstable
upstream API. Any new pin would have to be similarly conservative.

**Comment by bnavigator** [comment]
Any chance to bump it to openapi-core 0.18? We have a gordian knot with
 * openapi-spec-validator 0.6 (#403)
 * openapi-schema-validator 0.6 
 * jsonschema 4.18
