### ISSUE TITLE
URL handling cleanup

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab_server#66]
* Normalize paths to handle leading and trailing slashes (e.g.default_url, base_url)
* Get rid of page_url in favor of the existing default_url
* Rename publicUrl -> staticUrl
* Rename frontendUrl -> fullStaticUrl
* If base_url is included, prepend a field with `full`, eg: * fullStaticUrl * fullMathjaxUrl
* change from `/lab/static/` to `/static/lab` in preparation for https://github.com/jupyter/jupyter_server/pull/48

This requires a coordinated change with Jupyterlab and should be in a 1.0alpha version of this library

**Comment by echarles** [comment]
Is this to prepare `jupyterlab` transition from `notebook` to `jupyterlab_server`?

**Comment by blink1073** [comment]
The only change affected by `notebook` -> `jupyterlab_server` for us is to change from `/lab/static/*` to `/static/lab/*`, so I suppose we should do that here as well :smile:
