### ISSUE TITLE
Release with Listings Handler

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab_server#83]
Hi, https://github.com/jupyterlab/jupyterlab_server/pull/82 has just been merged and provides an additional Handler for the Listings.

There is no breaking change and previous jupyterlab version will continue to work transparently with that change.

For JupyterLab 2.1 release, we need a release of jupyterlab_server with that change.

Latest version is `1.0.7`. I am not sure what version policy to apply here, but my feeling is that going to `1.0.8` is OK.

Can someone pick this?

**Comment by blink1073** [comment]
Released as 1.1.0 since it was an API addition.  Cheers!

**Comment by echarles** [comment]
Thx @blink1073. 1.1.0 makes more sense.
